#PEEK TREND (trend follow stoploss)
closeRatio = 2
highRatio = 1
peekPercentage = 0.92
peekShift =50

# SMA INDICATOR
SMA_long = 300
SMA_short = 30

# RSI BULL
BULL_RSI = 10
BULL_RSI_high = 80
BULL_RSI_low = 60

# RSI BEAR
BEAR_RSI = 15
BEAR_RSI_high = 40
BEAR_RSI_low = 20

# MODIFY RSI (depending on ADX)
BULL_MOD_high = 5
BULL_MOD_low = -5
BEAR_MOD_high = 15
BEAR_MOD_low = -5

# ADX
ADX = 3
ADX_high = 70
ADX_low = 50

# PING PONG
PINGPONG_GAINS_PERCENTAGE = 2

