# VMApredict 7 optimized towards TRON
# If you still use gekko consider upgrade 
# to green gekko (gekko has ended).

[Swings]  
# Here the main constants

# magica    = used in long buy price dips
# mediumout = used in short sell
# shortsight= used in short sell

#these 4 can now be in a fractions!
# ea 0.01 = 1%
# based upon long moving average

Magica         = 0.0325
MediumOut   = 0.028  
ShortSight     = 0.96
ShortSightMult = 1.1
HighShot       = 0.088

# if you dont want fractions set below to false!
UseFractions = true  


# downhill = sell after price drop since highest
# highshot = short after price jump 2 new candles
# bullseye = sell if raised this much since bought
# daystop = max los, stops trade till next day

# those are still fixed numbers
DownHill = 0.002
BullsEye = 800    
DayStop  = 1000   

#Daystop after each downhill 
DownHillStop = true

[ForcastTrend] 
# forcast trend tulip indicator
Short  =  6 
Medium = 17
Long   = 50

[PeriodAverage] 
# moving averages
Short  = 5 
Medium = 25
Long   = 250

[VolumePeriodAverage]
# volume moving averages  
Short  = 7  
Medium = 30
Long   = 50

[RSISafety] 
# go short when above percentage
# wait buy  if RSI> rsiWait
# using x candles
RSIShort   = 0.96
RSIWait    = 0.88
RSIcandles = 6
